package top.yinxiaokang.others;

/**
 * @author yinxk
 * @date 2018/7/6 14:28
 */

import java.util.HashMap;

@SuppressWarnings("SpellCheckingInspection")
class DataBaseMap{

    public static HashMap<String,String> columnMap =  new HashMap<String, String>(){

        @Override
        public String get(Object key) {

            String object = super.get(key);

            return object != null ? object : (String) key;
        }

        {
            this.put("classify_name","分类名称");

            // // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='组织管理-分类表';
            this.put("FZR","负责人");
            this.put("LXDH","联系电话");
            this.put("MingCheng","名称");
            //// ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='组织管理-部门表';
            this.put("LXDH","联系电话");
            this.put("QQH","QQ号");
            this.put("RZSJ","入职时间");
            this.put("WXH","微信号");
            this.put("XingBie","性别");
            this.put("XingMing","姓名");
            this.put("XueLi","学历");
            this.put("YHTX","用户头像");
            this.put("YouXiang","邮箱");
            this.put("ZhangHao","账号");
            //// ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='账户管理-员工表';
            this.put("classify_id","分类ID");
            this.put("module_name","模块名称");
            //// ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='组织管理-模块表';
            this.put("BLSJ","办理时间");
            this.put("DiQu","地区");
            this.put("FZR","负责人");
            this.put("JingDu","经度");
            this.put("LXDH","联系电话");
            this.put("MingCheng","名称");
            this.put("SJWD","上级网点ID");
            this.put("WeiDu","维度");
            this.put("XXDZ","详细地址");
            //// ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='组织管理-网点表';
            this.put("action_code","请求代码");
            this.put("action_method","请求方法");
            this.put("action_url","请求路径");
            //// ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='权限api表';
            this.put("BeiZhu","备注");
            this.put("CaoZuo","操作");
            this.put("CZQD","操作渠道");
            this.put("CZY","操作员");
            this.put("QZSJ","签字图片");
            this.put("SHJG","审核结果");
            this.put("SHSJ","审核时间");
            this.put("YWLSH","业务流水号");
            this.put("YWWD","业务网点");
            this.put("YYYJ","原因/意见");
            this.put("ZhiWu","职务(操作员角色)");
            this.put("DDSJ","到达时间");
            this.put("YWLX","业务类型");
            this.put("CZYBH","操作员编号");
            //// ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='审核历史记录表';
            this.put("email","邮箱");
            this.put("password","密码");
            this.put("state","状态（1：启用，0：禁用）");
            this.put("type","用户类型（0：最高管理员，1：个人账户，2：员工账户，3：单位账户，4：房开商账号）");
            this.put("user_id","用户id");
            this.put("username","账号");
            // // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='认证表';
            this.put("acct","账户账号");
            this.put("amt","交易金额");
            this.put("available_amt","可用金额");
            this.put("balance","余额");
            this.put("book_list_no","笔号");
            this.put("book_no","册号");
            this.put("bus_seq_no","业务流水号");
            this.put("curr_iden","钞汇");
            this.put("curr_no","币种");
            this.put("date","交易日期,格式:YYYYMMDD");
            this.put("host_seq_no","银行主机流水号");
            this.put("is_make_acc","是否已做账: 0:是,1:否,null:自动对账业务");
            this.put("notice_no","通知编号");
            this.put("open_bank_no","开户机构号");
            this.put("opponent_acct","交易对手账号");
            this.put("opponent_bank_no","交易对手行号");
            this.put("opponent_name","交易对手户名");
            this.put("overdraft","可透支余额");
            this.put("redo","冲正标识");
            this.put("remark","备注");
            this.put("summary","摘要");
            this.put("time","交易时间,格式:HHMMSS");
            this.put("tx_code","银行交易代码");
            this.put("voucher_no","凭证号码");
            this.put("voucher_type","凭证种类");
            //// ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='结算平台-账户资金变动通知表';
            this.put("bank_name","银行全称");
            this.put("chgno","联行号");
            this.put("code","银行代码，联行号前三位");
            this.put("node","银行节点号");
            this.put("area_code","地区编码");
            // // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='结算平台-银行信息表';
            this.put("business_seq_no","业务流水号");
            this.put("no","批量文件中的序号");
            this.put("rtn_code","响应信息（00000：成功，其他：失败）");
            this.put("rtn_message","报文信息");
            // // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='结算平台-业务表';
            this.put("BeiZhu","备注");
            this.put("KHBH","客户编号");
            this.put("LXDH","联系电话");
            this.put("LXR","联系人");
            this.put("node","银行节点号");
            this.put("WDDZ","网点地址");
            this.put("XDCKJE","协定存款金额");
            this.put("YHDM","银行代码");
            this.put("YHMC","银行名称");
            //  // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='公积金中心签约银行表';
            this.put("bank_name","银行名称");
            this.put("code","银行编码");
            this.put("node","银行节点号");
            //  // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='结算平台-银行节点信息表';
            this.put("batch_no","批量编号");
            this.put("bus_type","业务类型");
            this.put("business_seq_no","业务流水号");
            this.put("fine_host_seq_no","贷款违约金银行主机流水号");
            this.put("host_seq_no","银行主机流水号");
            this.put("int_host_seq_no","贷款罚息银行主机流水号");
            this.put("pen_host_seq_no","利息银行主机流水号");
            this.put("receive_node","接收方节点号");
            this.put("receive_seq_no","接收方流水号");
            this.put("rtn_message","报文信息");
            this.put("send_date","交易日期");
            this.put("send_seq_no","发送方流水号");
            this.put("txCode","交易代码");
            this.put("tx_status","交易状态（0：成功，1：失败，2：其他,处理中或状态未知）");
            this.put("type","类型(1:单笔交易且无交易结果,2:单笔交易有交易结果,3:批量交易且无交易结果,4:批量交易且有交易结果)");
            this.put("cust_no","客户编号");
            // // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='结算平台-发送方流水表';
            this.put("context","转移上下文");
            this.put("taskid","业务流水号");
            //  // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='业务状态转换上下文表';
            this.put("BeiZhu","备注");
            this.put("BLZL","办理资料");
            this.put("CZMC","操作名称");
            this.put("CZY","操作员");
            this.put("CZYY","操作原因");
            this.put("DJJE","冻结金额");
            this.put("DWZH","单位账号");
            this.put("GRZH","个人账号");
            this.put("SLSJ","受理时间");
            this.put("SXNY","生效年月");
            this.put("YWLSH","业务流水号");
            this.put("YWWD","业务网点");
            this.put("GRYWMX","个人业务明细");
            // // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='针对“冻结个人账户”“解冻个人账户”“封存个人账户”“启封个人账户”';
            this.put("BLZL","办理资料");
            this.put("CSNY","出生年月 YYYY-MM");
            this.put("CZY","操作员");
            this.put("DWZH","单位账号");
            this.put("DZYX","电子邮箱");
            this.put("GDDHHM","固定电话号码");
            this.put("GJHTQYWLX","归集和提取业务类型");
            this.put("GJJSCHJNY","公积金首次汇缴年月");
            this.put("GRCKZHHM","个人存款账户号码");
            this.put("GRCKZHKHYHDM","个人存款账户开户银行代码。 联行号前三位");
            this.put("GRCKZHKHYHMC","个人存款账户开户银行名称");
            this.put("GRJCJS","个人缴存基数");
            this.put("GRZH","个人账号");
            this.put("GRZHYE","个人账户余额");
            this.put("HYZK","婚姻状况");
            this.put("JTYSR","家庭月收入");
            this.put("JTZZ","家庭住址");
            this.put("SJHM","手机号码");
            this.put("SLSJ","受理时间");
            this.put("XingBie","性别");
            this.put("XingMing","姓名");
            this.put("XMQP","姓名全拼");
            this.put("XueLi","学历");
            this.put("YWLSH","业务流水号");
            this.put("YWWD","业务网点");
            this.put("YZBM","邮政编码 YD/T 603");
            this.put("ZhiCheng","职称");
            this.put("ZhiWu","职务");
            this.put("ZhiYe","职业");
            this.put("ZJHM","证件号码");
            this.put("ZJLX","证件类型");
            this.put("GRYWMX","个人业务明细");
            // // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='针对“设立个人账户““变更个人账户”';
            this.put("BLZH","保留账号（仅合并业务）");
            this.put("BLZL","办理资料");
            this.put("CZMC","操作名称");
            this.put("CZY","操作员");
            this.put("DWZH","单位账号");
            this.put("GRZH","个人账号");
            this.put("HBZH","合并账号集合（仅合并业务）");
            this.put("SLSJ","受理时间");
            this.put("XingMing","姓名");
            this.put("YWLSH","业务流水号");
            this.put("YWWD","业务网点");
            this.put("ZJHM","证件号码");
            this.put("ZJLX","证件类型");
            this.put("GRYWMX","个人业务明细");
            // // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='针对“合并个人账户”';
            this.put("BeiZhu","备注");
            this.put("GRZH","个人账号");
            this.put("XingMing","姓名");
            this.put("ZRDWMC","转入单位名称");
            this.put("ZRDWZH","转入单位账号");
            this.put("NBZYXQ","内部转移详情");
            // // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='针对账户内部转移，每个业务的转移账号列表';
            this.put("GRZH","职工个人账号");
            this.put("YDWYJCE","原单位下单位月缴存额");
            this.put("YGRJCJS","原单位下个人月缴存基数");
            this.put("YGRYJCE","原单位下个人月缴存额");
            this.put("ZCDW","转出单位账号");
            this.put("ZRDW","转入单位账号");
            this.put("ZYSDNGJYE","转移时个人账户当年归集余额");
            this.put("ZYSGRZHYE","转移时个人账户余额");
            this.put("ZYSSNJZYE","转移时个人账户上年结转余额）");
            this.put("SXNY","转移时默认的的生效年月，用于清册业务");
            // // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='个人开户时，保存个人账户转移前的信息';
            this.put("ZCDWMC","转出单位名称（仅内部转移业务）");
            this.put("ZCDWZH","转出单位账号（仅内部转移业务）");
            this.put("ZYSXNY","转移生效年月（仅内部转移业务）");
            this.put("DWYWMX","单位业务明细");
            // // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='针对“个人内部转移”';
            this.put("GRZH","个人账号");
            this.put("TZHGRJS","调整后个人基数");
            this.put("TZQGRJS","调整前个人基数");
            this.put("JSTZXQ","基数调整详情");
            //  // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='个人基数调整';
            this.put("FSRS","发生人数");
            this.put("SXNY","生效年月");
            this.put("DWYWMX","单位业务明细");
            //  // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='个人基数调整';
            this.put("BeiZhu","备注");
            this.put("BJSJ","办结时间");
            this.put("BLR","办理人");
            this.put("BLZL","办理资料");
            this.put("CZMC","操作名称");
            this.put("CZY","操作员");
            this.put("CZYY","操作原因");
            this.put("DDSJ","到达时间");
            this.put("DJJE","冻结金额");
            this.put("DLRXM","代理人姓名");
            this.put("DLRZJHM","代理人证件号码");
            this.put("DLRZJLX","代理人证件类型");
            this.put("GRCKZHHM","个人存款账户号码");
            this.put("GRCKZHKHYHMC","个人存款账户开户银行名称");
            this.put("HuMing","户名");
            this.put("JBRXM","经办人姓名");
            this.put("JBRZJHM","经办人证件号码");
            this.put("JBRZJLX","经办人证件类型");
            this.put("JZPZH","记账凭证号");
            this.put("LJTQJE","累计提取金额");
            this.put("SHBTGYY","审核不通过原因");
            this.put("SHSJ","审核时间（即审核列表中的受理时间）");
            this.put("SHYBH","审核员编号");
            this.put("SHYJ","审核意见");
            this.put("SLSJ","受理时间");
            this.put("STEP","状态机状态");
            this.put("XCTQRQ","下次提取日期");
            this.put("XHTQFSLXE","销户提取发生利息额");
            this.put("YHKE","月还款额");
            this.put("YWWD","业务网点");
            this.put("YZM","验证码");
            this.put("ZCDW","转出单位");
            this.put("JQE","结清额");
            this.put("HKFS","还款方式");
            this.put("DQYE","当前余额");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='个人业务明细扩展表';
            this.put("YWLSH","业务流水号");
            this.put("YWLX","业务类型:启封04、封存05、调基10、调比75");
            this.put("YWMS","业务描述");
            this.put("ZXCS","执行次数");
            this.put("ZXSJ","执行时间");
            this.put("ZXZT","执行状态,00未执行，01执行成功，02执行失败");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='归集定时任务表';
            this.put("FXZH","发薪账号");
            this.put("FXZHHM","发薪账号户名");
            this.put("FXZHKHYH","发薪账号开户银行");
            this.put("ZSYE","暂收余额");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='缴存单位信息扩展表';
            this.put("BeiZhu","备注");
            this.put("BJSJ","办结时间");
            this.put("BLZL","办理资料");
            this.put("CZMC","操作名称");
            this.put("CZY","操作员");
            this.put("DDSJ","到达时间");
            this.put("FCHXHYY","封存或销户原因");
            this.put("JBRXM","经办人姓名");
            this.put("JBRZJHM","经办人证件号码");
            this.put("JBRZJLX","经办人证件类型");
            this.put("JZPZH","记账凭证号");
            this.put("QTCZYY","其他操作原因（如启封等等）");
            this.put("SHBTGYY","审核不通过原因");
            this.put("SHSJ","审核时间");
            this.put("SHYBH","审核员编号");
            this.put("SLSJ","受理时间");
            this.put("STEP","状态机状态");
            this.put("SXNY","生效年月");
            this.put("YWWD","业务网点");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='缴存单位业务明细扩展表';
            this.put("DWZHYE","单位账户余额");
            this.put("DWYJCE","单位月缴存额");
            this.put("GRJCJS","个人缴存基数");
            this.put("GRYJCE","个人月缴存额");
            this.put("GRZH","个人账号");
            this.put("QCQRDH","清册确认单号");
            this.put("QCXQ","清册详情");
            this.put("GRZHYE","个人账户余额");
            this.put("GRZHZT","个人账户状态");
            this.put("QCFSE","清册发生额");
            this.put("YJCE","月缴存额");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='单位清册详情';
            this.put("DWFCRS","单位封存人数");
            this.put("DWJCBL","单位缴存比例");
            this.put("DWJCRS","单位缴存人数");
            this.put("DWYJCEHJ","单位月缴存额合计");
            this.put("GRJCBL","个人缴存比例");
            this.put("GRYJCEHJ","个人月缴存额合计");
            this.put("QCNY","清册年月");
            this.put("QCQRDH","清册确认单号");
            this.put("DWYWMX","单位业务明细");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='单位缴存清册';
            this.put("SXNY","生效年月");
            this.put("TZQDWBL","调整前单位比例");
            this.put("TZQGRBL","调整前个人比例");
            this.put("TZHDWBL","调整后单位比例");
            this.put("TZHGRBL","调整后个人比例");
            this.put("DWYWMX","单位业务明细");
            this.put("TZZDWBL","调整后单位比例");
            this.put("TZZGRBL","调整后个人比例");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='单位比例调整';
            this.put("BeiZhu","备注");
            this.put("BLZL","办理资料");
            this.put("CZMC","操作名称");
            this.put("CZY","操作员");
            this.put("DWLB","单位类别");
            this.put("DWXHYY","单位销户原因 附A.3");
            this.put("DWZH","单位账号");
            this.put("FCHXHYY","封存或销户原因");
            this.put("QTCZYY","其他操作原因（如启封等等）");
            this.put("SLSJ","受理时间");
            this.put("YWLSH","业务流水号");
            this.put("YWWD","业务网点");
            this.put("DWYWMX","单位业务明细");
            this.put("BeiZhu","备注");
            this.put("BLZL","办理资料");
            this.put("CZMC","操作名称");
            this.put("CZY","操作员");
            this.put("DDSJ","到达时间");
            this.put("DJSYYZ","登记使用印章");
            this.put("DJZCH","登记注册号");
            this.put("DWCZHM","单位传真号码");
            this.put("DWDZ","单位地址");
            this.put("DWDZXX","单位电子信箱");
            this.put("DWFRDBXM","单位法人代表姓名");
            this.put("DWFRDBZJHM","单位法人代表证件号码");
            this.put("DWFRDBZJLX","单位法人代表证件类型 01：身份证 02：军官证 03：护照 04：外国人永久居留证 99：其他");
            this.put("DWFXR","单位发薪日");
            this.put("DWJCBL","单位缴存比例");
            this.put("DWJJLX","单位经济类型 参考GB/T 12402-2000");
            this.put("DWLB","单位类别");
            this.put("DWLSGX","单位隶属关系 参考GBT12404-1997");
            this.put("DWLXDH","单位联系电话");
            this.put("DWMC","单位名称");
            this.put("DWSCHJNY","单位首次汇缴年月");
            this.put("DWSLRQ","单位设立日期 YYYYMMDD GB/T 7408");
            this.put("DWSSHY","单位所属行业 GB/T 4754");
            this.put("DWYB","单位邮编 参照：YD/T 603");
            this.put("DWZH","单位账号");
            this.put("FXZH","发薪账户");
            this.put("FXZHHM","发薪账户户名");
            this.put("FXZHKHYH","发薪账户开户银行");
            this.put("GRJCBL","个人缴存比例");
            this.put("JBRGDDHHM","经办人固定电话号码");
            this.put("JBRSJHM","经办人手机号码");
            this.put("JBRXM","经办人姓名");
            this.put("JBRZJHM","经办人证件号码 GB11643");
            this.put("JBRZJLX","经办人证件类型 01：身份证 02：军官证 03：护照 04：外国人永久居留证 99：其他");
            this.put("KGQK","控股情况");
            this.put("PZJGJB","批准机关级别");
            this.put("PZJGMC","批准机关名称");
            this.put("SLSJ","受理时间 yyyy-MM-dd hh:mm");
            this.put("STYHDM","受托银行代码");
            this.put("STYHMC","受托银行名称");
            this.put("XZQY","行政区域");
            this.put("YWLSH","业务流水号");
            this.put("YWMXLX","业务明细类型 附A.5");
            this.put("YWWD","业务网点");
            this.put("ZZJGDM","组织机构代码 GB11714");
            this.put("DWYWMX","单位业务明细");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='针对“单位账户设立（开户）”“单位账户变更”';
            this.put("BJYY","补缴原因");
            this.put("DWBJE","单位补缴额");
            this.put("GRBJE","个人补缴额");
            this.put("GRZH","个人账号");
            this.put("BJMX","补缴明细");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='单位补缴明细';
            this.put("BJFS","补缴方式");
            this.put("QCQRDH","清册确认单号");
            this.put("DWYWMX","单位业务明细");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='单位补缴';
            this.put("CJFS","催缴方式");
            this.put("CJR","催缴人");
            this.put("CJSJ","催缴时间");
            this.put("ZDCJ","自动催缴");
            this.put("DWYWMX","单位业务明细");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='单位催缴';
            this.put("HJKSSJ","缓缴开始时间");
            this.put("HJJSSJ","缓缴结束时间");
            this.put("QIANNIANKS","前年亏损");
            this.put("QIANNIANRJGZ","前年人均工资");
            this.put("QIANNIANYL","前年盈利");
            this.put("QUNIANKS","去年亏损");
            this.put("QUNIANRJGZ","去年人均工资");
            this.put("QUNIANYL","去年盈利");
            this.put("DWYWMX","单位业务明细");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='单位缓缴';
            this.put("CJYY","错缴原因");
            this.put("DWCJJE","单位错缴金额");
            this.put("GRCJJE","个人错缴金额");
            this.put("GRZH","个人账号");
            this.put("CJXQ","错缴详情");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='单位错缴详情';
            this.put("JCGZNY","缴存更正年月");
            this.put("QCQRDH","清册确认单号");
            this.put("SKYHDM","收款银行代码");
            this.put("SKYHHM","收款银行户名");
            this.put("SKYHMC","收款银行名称");
            this.put("SKYHZH","收款银行账户");
            this.put("DWYWMX","单位业务明细");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='单位错缴';
            this.put("GRZH","个人账号");
            this.put("QCQRDH","清册确认单号");
            this.put("HJXQ","汇缴详情");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='单位汇缴详情';
            this.put("HBJNY","汇补缴年月");
            this.put("HJFS","汇缴方式");
            this.put("QCQRDH","清册确认单号");
            this.put("STYHDM","受托银行代码");
            this.put("STYHMC","受托银行名称");
            this.put("STYHZH","受托银行账户");
            this.put("DWYWMX","单位业务明细");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='单位汇缴';
            this.put("BLR","办理人");
            this.put("BLZL","办理资料");
            this.put("CZY","操作员");
            this.put("DLRXM","代理人姓名");
            this.put("DLRZJHM","代理人证件号码");
            this.put("DLRZJLX","代理人证件类型");
            this.put("FSE","发生额");
            this.put("GRCKZHHM","个人存款账户号码");
            this.put("GRCKZHKHYHMC","个人存款账户开户银行名称");
            this.put("GRZH","个人账号");
            this.put("HuMing","户名");
            this.put("ICL","是否处理");
            this.put("JZRQ","记账日期 YYYYMMDD");
            this.put("LJTQJE","累计提取金额");
            this.put("SLSJ","受理时间");
            this.put("TQFS","提取方式");
            this.put("TQYY","提取原因 附A.7");
            this.put("XCTQRQ","下次提取日期");
            this.put("XHYY","销户原因 附A.7");
            this.put("YHKE","月还款额");
            this.put("YWMXLX","业务明细类型 附A.5");
            this.put("YWWD","业务网点");
            this.put("GRYWMX","个人业务明细");
            this.put("HKFS","还款方式");
            this.put("JQE","jieqinge");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='提取业务信息副表';
            this.put("BJJE","本金金额");
            this.put("DZYX","电子邮箱");
            this.put("GJJSCHJNY","公积金首次汇缴年月");
            this.put("GRJZNY","个人缴至年月");
            this.put("GRZHZTLX","个人账户状态类型");
            this.put("LXJE","利息金额");
            this.put("SFDJ","是否冻结：01正常/02冻结");
            this.put("XCTQRQ","下次提取日期");
            this.put("GRZL","个人资料");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='个人信息扩展表';
            this.put("MingCheng","名称");
            this.put("SXRQ","生效日期");
            this.put("XGZ","修改值");
            this.put("HKNLXS","还款能力系数");
            this.put("DNGRZFGJJCKLL","当年个人住房公积金存款利率");
            this.put("SNGRZFGJJCKLL","上年个人住房公积金存款利率");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='政策信息';
            this.put("BeiZhu","备注");
            this.put("CZHM","传真号码");
            this.put("DJSYYZ","登记使用印章");
            this.put("DJZCH","登记注册号");
            this.put("DWLB","单位类别");
            this.put("DWLXDH","单位联系电话");
            this.put("DWSCHJNY","单位首次汇缴年月");
            this.put("DWXZQY","单位行政区域");
            this.put("KGQK","控股情况");
            this.put("PZJGJB","批准机关级别");
            this.put("PZJGMC","批准机关名称");
            this.put("DWZL","单位资料");
            this.put("KHWD","开户网点");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='缴存单位信息扩展表';
            this.put("code","编码");
            this.put("name","名称");
            this.put("no","序号");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='字典表';
            this.put("parent","请求方法");
            this.put("name","请求路径");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='权限api表';
            this.put("SHA1","SHA1");
            this.put("count","获取次数");
            this.put("name","文件名");
            this.put("path","保存路径");
            this.put("size","文件大小");
            this.put("type","文件类型");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='文件';
            this.put("JieZRQ","截至日期");
            this.put("JZR","结账人");
            this.put("JZRQ","结账日期");
            this.put("KJND","会计年度");
            this.put("KJQJ","会计期间");
            this.put("QSRQ","起始日期");
            this.put("SFJS","是否结算");
            this.put("cFinanceAccountSets","账套");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='会计期间';
            this.put("JZR","建账人");
            this.put("JZRQ","建账日期");
            this.put("KJZG","会计主管");
            this.put("QYQJ","启用期间");
            this.put("ZTBZ","备注");
            this.put("ZTMC","账套名称");
            this.put("QYRQ","启用日期");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='账套表';
            this.put("amt","交易金额(required)");
            this.put("acct_name","户名");
            this.put("acct_no","账号");
            this.put("deposit_begin_date","存入日期");
            this.put("deposit_end_date","到期日期");
            this.put("deposit_period","存期");
            this.put("extend_deposit_type","转存方式");
            this.put("interest_rate","利率");
            this.put("khyhmc","开户银行名称");
            this.put("part_extend_deposit_acct_no","利息转存转入账号");
            this.put("ywlsh","业务流水号");
            this.put("extension","理财业务扩展表");
            this.put("book_list_no","笔号");
            this.put("book_no","册号");
            this.put("DQCKBH","定期存款编号");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='活期转定期';
            this.put("BLSJ","办理时间");
            this.put("CZNR","操作内容");
            this.put("CZQD","操作渠道");
            this.put("CZY","操作员");
            this.put("STEP","状态机状态");
            this.put("YWLSH","业务流水号");
            this.put("YWWD","业务网点");
            this.put("ZHCLRY","最后处理人员");
            this.put("BJSJ","审核时间");
            this.put("DDSJ","审核时间");
            this.put("SHSJ","审核时间");
            this.put("SHYBH","审核员编号");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='财务-业务流程表';
            this.put("BeiZhu","备注");
            this.put("CJR","创建人");
            this.put("CJSJ","创建时间");
            this.put("DFKM","贷方科目");
            this.put("JFKM","借方科目");
            this.put("MBBH","模板编号");
            this.put("YWMC","业务名称");
            this.put("SFYSY","是否已使用");
            this.put("YWMCID","业务名称ID");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='业务凭证设置';
            this.put("BLZL","办理资料");
            this.put("CZY","操作员");
            this.put("SLSJ","受理时间");
            this.put("YWLSH","业务流水号");
            this.put("YWSJ","业务数据json");
            this.put("ZJYWLX","资金业务类型");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='日常业务处理 基础表';
            this.put("CJR","创建人");
            this.put("CJSJ","创建时间");
            this.put("SFMR","是否默认");
            this.put("SFRC","是否日常");
            this.put("YWMC","分类名称");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='日常业务分类管理表';
            this.put("CJR","创建人");
            this.put("CJSJ","创建时间");
            this.put("SFMR","是否默认");
            this.put("SFSY","是否使用");
            this.put("YWMC","业务名称");
            this.put("SFZD","是否自动");
            this.put("SFJSPT","是否走结算平台");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='日常业务管理表';
            this.put("BLZL","办理资料");
            this.put("YWSJ","业务数据json");
            this.put("ZJYWLX","资金业务类型");
            this.put("RCCWCL","日常业务处理");
            this.put("MBBH","凭证模板编号");
            this.put("YWMCID","业务名称ID");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='日常业务处理 副表';
            this.put("acct_no","账号");
            this.put("acct_status","账户状态 0:正常 1:销户 :没收 3:上缴 9:其他");
            this.put("beg_amt","开户金额");
            this.put("book_list_no","笔号");
            this.put("book_no","册号");
            this.put("deposit_begin_date","存入日期");
            this.put("deposit_end_date","到期日期");
            this.put("deposit_period","存期");
            this.put("draw_amt","实际金额");
            this.put("freeze_type","冻结状态 0:正常 1:冻结 3:部分冻结 4:其它");
            this.put("interest","结清利息");
            this.put("interest_rate","利率");
            this.put("khyhmc","开户银行名称");
            this.put("loss_flag","挂失标志 0:正常 1:挂失");
            this.put("DQCKBH","定期存款编号");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='定期余额';
            this.put("acct_name","户名");
            this.put("acct_no","账号");
            this.put("book_list_no","笔号");
            this.put("book_no","册号");
            this.put("deposit_begin_date","存入日期");
            this.put("deposit_end_date","到期日期");
            this.put("deposit_period","存期");
            this.put("deposti_amt","实际金额");
            this.put("draw_amt","支取金额");
            this.put("interest_rate","利率");
            this.put("khyhmc","开户银行名称");
            this.put("ywlsh","业务流水号");
            this.put("zqqk","支取情况");
            this.put("extension","理财业务扩展表");
            this.put("DQCKBH","定期存款编号");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='定期支取';
            this.put("BEIZHU","备注");
            this.put("BJSJ","办结时间");
            this.put("CZMC","操作名称");
            this.put("CZY","操作员");
            this.put("DDSJ","到达时间");
            this.put("SHSJ","审核时间（即审核列表中的受理时间）");
            this.put("STEP","状态机状态");
            this.put("YWLX","业务类型 09：定期存款 10：定期支取 11：通知存款 12：通知存款支取");
            this.put("RGCL","是否人工处理 0:是 1:否");
            this.put("SBYY","失败原因");
            this.put("SHYBH","审核员编号");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='理财业务扩展表';
            this.put("ChuNa","出纳");
            this.put("CWZG","财务主管");
            this.put("CZNR","操作内容");
            this.put("DFHJ","贷方合计");
            this.put("FuHe","复核");
            this.put("HSDW","核算单位");
            this.put("JFHJ","借方合计");
            this.put("JiZhang","记账");
            this.put("KMYEFX","科目余额方向 附A.27");
            this.put("SFJZ","是否结账");
            this.put("SFZJL","是否主记录");
            this.put("YWLSH","业务流水号");
            this.put("YWLX","业务类型");
            this.put("YWMC","业务名称");
            this.put("ZhiDan","制单");
            this.put("cBankAccChangeNotice","账户变动通知回执单");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='记账凭证信息 扩展表';
            this.put("BBLX","报表类型");
            this.put("BBQJ","报表期间");
            this.put("BBSJ","报表数据");
            this.put("NAME","报表名字");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='财务报表';
            this.put("BYJS","本月减少");
            this.put("BYYE","本月余额");
            this.put("BYZJ","本月增加");
            this.put("KMBH","科目编号 附A.25");
            this.put("KMJB","科目级别");
            this.put("KMMC","科目名称");
            this.put("KMYEFX","科目余额方向 附A.27");
            this.put("SYYE","上月余额");
            this.put("cFinanceAccountPeriod","会计期间");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='科目余额表';
            this.put("BJJS","本季减少");
            this.put("BJYE","本季余额");
            this.put("BJZJ","本季增加");
            this.put("JiDu","季度1，2，3，4");
            this.put("KMBH","科目编号 附A.25");
            this.put("KMJB","科目级别");
            this.put("KMMC","科目名称");
            this.put("KMYEFX","科目余额方向 附A.27");
            this.put("NianFen","年份2017");
            this.put("SJYE","上季余额");
            this.put("Verify","本账是否核对");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='科目余额季度表';
            this.put("BNJS","本年减少");
            this.put("BNYE","本年余额");
            this.put("BNZJ","本年增加");
            this.put("KMBH","科目编号 附A.25");
            this.put("KMJB","科目级别");
            this.put("KMMC","科目名称");
            this.put("KMYEFX","科目余额方向 附A.27");
            this.put("NianFen","年份2017");
            this.put("SNYE","上年余额");
            this.put("Verify","本账是否核对");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='科目余额年度表';
            this.put("BeiZhu","备注");
            this.put("CZKZ","赤字控制");
            this.put("KMJM","科目简码");
            this.put("SJKM","上级科目");
            this.put("type","科目属性（01：收入、02：支出）");
            this.put("KMXZ","科目性质");
            this.put("SFMR","是否默认");
            this.put("SFYSY","是否已使用");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='科目信息 扩展表';
            this.put("FKHM","付款户名");
            this.put("FKZH","付款账号");
            this.put("HRJE","汇入金额");
            this.put("HRSJ","汇入时间,格式:YYYYMMDD");
            this.put("JZPZH","记账凭证号");
            this.put("SKHM","收款户名");
            this.put("SKZH","收款账号");
            this.put("state","状态（1：已分配，0：未分配）");
            this.put("ZhaiYao","摘要");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='暂收记录表';
            this.put("YWMCID","业务名称ID");
            this.put("ZJYWLX","资金业务类型");
            this.put("ZJYWLXBM","资金业务类型编码");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='资金业务类型与业务类型对照表';
            this.put("HKZH","还款账号");
            this.put("JKRXM","借款人姓名");
            this.put("SBYY","失败原因");
            this.put("XQBJJE","下期本金金额");
            this.put("XQDKYE","下期贷款余额");
            this.put("XQFSE","下期发生额");
            this.put("XQLXJE","下期利息金额");
            this.put("YWZT","业务状态");
            this.put("RGCL","是否人工处理 0:是 1:否");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='个人贷款业务明细拓展';
            this.put("BLZL","办理资料");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='抵押表';
            this.put("YWZT","业务状态");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='个人住房贷款逾期登记信息副表 表6.0.7';
            this.put("CKJRJG","存款金融机构");
            this.put("LiLv","利率");
            this.put("ZHLX","专户类型");
            this.put("ZHXZ","专户性质");
            this.put("ZJYE","资金余额");
            this.put("cFinanceAccountPeriod","会计期间");
            this.put("CKLX","存款类型");
            this.put("XuHao","序号");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='住房公积金银行存款情况表';
            this.put("CKLX","存款类型");
            this.put("LiLv","利率");
            this.put("ZHXZ","专户性质");
            this.put("ZJYE","资金余额");
            this.put("cFinanceAccountPeriod","会计期间");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='住房公积金银行存款情况汇总表';
            this.put("DaiMa","代码");
            this.put("JLDW","计量单位");
            this.put("ShuLiang","数量");
            this.put("XuHao","序号");
            this.put("ZBMC","指标名称");
            this.put("cFinanceAccountPeriod","会计期间");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='住房公积金缴存使用情况表';
            this.put("DKZH","贷款账号");
            this.put("GYYCHKE","该月一次还款额");
            this.put("HKFS","还款方式");
            this.put("HKJE","还款金额");
            this.put("HKLX","还款类型");
            this.put("HKQC","还款期次");
            this.put("JKRXM","借款人姓名");
            this.put("JKRZJHM","借款人证件号码");
            this.put("JYLX","节约利息");
            this.put("MYDJ","每月递减");
            this.put("SYBJ","剩余本金");
            this.put("SYLX","剩余利息");
            this.put("SYQC","剩余期次");
            this.put("XMYDJ","新每月递减");
            this.put("XYHKE","新月还款额");
            this.put("XZHHKQX","新最后还款期限");
            this.put("YDKKRQ","约定扣款日期");
            this.put("YQKZJ","逾期款总计");
            this.put("YSYHKE","原首月还款额");
            this.put("YZHHKQX","原最后还款期限");
            this.put("GRYWMX","个人业务明细");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='还款申请表';
            this.put("BeiZhu","备注");
            this.put("DKBL","贷款比例");
            this.put("DYS","单元数");
            this.put("JGRQ","竣工日期");
            this.put("KSDYH","开始单元号");
            this.put("LDMH","楼栋名/号");
            this.put("XYRQ","协议日期");
            this.put("cLoanEatateProjectBasic","楼盘项目");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='楼栋信息';
            this.put("BeiZhu","备注");
            this.put("DKBL","贷款比例");
            this.put("DYS","单元数");
            this.put("JGRQ","竣工日期");
            this.put("KSDYH","开始单元号");
            this.put("LDMH","楼栋名/号");
            this.put("XYRQ","协议日期");
            this.put("loanEatateProjectVice","楼栋信息");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='楼栋信息';
            this.put("AJXYRQ","按揭协议日期");
            this.put("BeiZhu","备注");
            this.put("BLZL","办理资料");
            this.put("BZJBL","保证金比例");
            this.put("CZY","操作员");
            this.put("HQTDDJ","获取土地单价");
            this.put("HQTDZJ","获取土地总价");
            this.put("JZZJE","建筑总金额");
            this.put("JZZMJ","建筑总面积");
            this.put("LPBH","楼盘编号");
            this.put("LPDZ","楼盘地址");
            this.put("LPMC","楼盘名称");
            this.put("LXDH","联系电话");
            this.put("LXR","联系人");
            this.put("SFBG","是否变更");
            this.put("SFQY","是否启用");
            this.put("YSXKZH","预售许可证号");
            this.put("YWWD","业务网点");
            this.put("cLoanHousingCompanyBasic","公司贷款基础表");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='楼盘项目';
            this.put("AJXYRQ","按揭协议日期");
            this.put("BeiZhu","备注");
            this.put("BLZL","办理资料");
            this.put("BZJBL","保证金比例");
            this.put("FKGS","房开公司");
            this.put("HQTDDJ","获取土地单价");
            this.put("HQTDZJ","获取土地总价");
            this.put("JZZJE","建筑总金额");
            this.put("JZZMJ","建筑总面积");
            this.put("LPBH","楼盘编号");
            this.put("LPDZ","楼盘地址");
            this.put("LPMC","楼盘名称");
            this.put("LXDH","联系电话");
            this.put("LXR","联系人");
            this.put("SFBG","是否变更");
            this.put("YSXKZH","预售许可证号");
            this.put("GRYWMX","个人业务明细");
            this.put("loanHousingCompanyVice","房开公司");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='楼盘项目';
            this.put("DKDBLX","贷款担保类型  （0：抵押 1：质押 2：保证 3：其他）");
            this.put("DKLX","贷款类型（0：公积金贷款 1：组合贷款 2：贴息贷款 3：其他）");
            this.put("DKQS","贷款期数");
            this.put("FWTS","房屋套数（0：一套 1：二套 2：三套 3：四套  5：五套及以上）");
            this.put("HKFS","还款方式（0：等额本息 1：等额本金 2：一次还款付息 3：自由还款方式 4：其他）");
            this.put("HTDKJE","合同贷款金额");
            this.put("HTDKJEDX","合同贷款金额大写");
            this.put("JKHTLL","借款合同利率");
            this.put("LLFSBL","利率浮动比例");
            this.put("WTKHYJCE","委托扣划月缴存额（0：是 1：否）");
            this.put("YWLSH","业务流水号");
            this.put("ZXLL","执行利率");
            this.put("cLoanHousingPersonInformationBasic","贷款个人信息基础表");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='基础-个人贷款资金信息表';
            this.put("DKDBLX","贷款担保类型  （0：抵押 1：质押 2：保证 3：其他）");
            this.put("DKLX","贷款类型（0：公积金贷款 1：组合贷款 2：贴息贷款 3：其他）");
            this.put("DKQS","贷款期数");
            this.put("FWTS","房屋套数（0：一套 1：二套 2：三套 3：四套  5：五套及以上）");
            this.put("HKFS","还款方式（0：等额本息 1：等额本金 2：一次还款付息 3：自由还款方式 4：其他）");
            this.put("HTDKJE","合同贷款金额");
            this.put("HTDKJEDX","合同贷款金额大写");
            this.put("JKHTLL","借款合同利率");
            this.put("LLFSBL","利率浮动比例");
            this.put("WTKHYJCE","委托扣划月缴存额（0：是 1：否）");
            this.put("ZXLL","执行利率");
            this.put("GRYWMX","个人业务明细");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='个人贷款资金信息表';
            this.put("BLZL","办理资料");
            this.put("BZFLX","保证方类型（0：个人 1：机构）");
            this.put("FRDBLXDH","法人代表联系电话");
            this.put("FRDBSFZHM","法人代表身份证号码");
            this.put("FRDBXJZDZ","法人代表现居住地址");
            this.put("FRDBXM","法人代表姓名");
            this.put("TXDZ","通讯地址");
            this.put("YWLSH","业务流水号");
            this.put("YZBM","邮政编码");
            this.put("guarantee_extenstions","保证表");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='保证表';
            this.put("BLZL","办理资料");
            this.put("DYFWXS","抵押房屋形式（0：住宅 （期房） 1：住宅（现房） 2：商铺 3：其他）");
            this.put("DYWFWZL","抵押物房屋坐落");
            this.put("DYWGYQRLXDH","抵押物共有权人联系电话");
            this.put("DYWGYQRSFZHM","抵押物共有权人身份证号码");
            this.put("DYWGYQRXM","抵押物共有权人姓名");
            this.put("DYWMC","抵押物名称");
            this.put("DYWPGJZ","抵押物评估价值");
            this.put("DYWSYQRLXDH","抵押物所有权人联系电话");
            this.put("DYWSYQRSFZHM","抵押物所有权人身份证号码");
            this.put("DYWSYQRXM","抵押物所有权人姓名");
            this.put("FWJG","房屋结构（0：框架 1：砖混 2：土木 3：其他）");
            this.put("FWMJ","房屋面积");
            this.put("QSZSBH","权属证书编号");
            this.put("YWLSH","业务流水号");
            this.put("guarantee_mortgage_extenstions","抵押表");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='抵押表';
            this.put("DYFWXS","抵押房屋形式（0：住宅 （期房） 1：住宅（现房） 2：商铺 3：其他）");
            this.put("DYWFWZL","抵押物房屋坐落");
            this.put("DYWGYQRLXDH","抵押物共有权人联系电话");
            this.put("DYWGYQRSFZHM","抵押物共有权人身份证号码");
            this.put("DYWGYQRXM","抵押物共有权人姓名");
            this.put("DYWMC","抵押物名称");
            this.put("DYWPGJZ","抵押物评估价值");
            this.put("DYWSYQRLXDH","抵押物所有权人联系电话");
            this.put("DYWSYQRSFZHM","抵押物所有权人身份证号码");
            this.put("DYWSYQRXM","抵押物所有权人姓名");
            this.put("FWJG","房屋结构（0：框架 1：砖混 2：土木 3：其他）");
            this.put("FWMJ","房屋面积");
            this.put("QSZSBH","权属证书编号");
            this.put("guaranteeMortgageVices","抵押副表");
            this.put("cLoanHousingGuaranteeContractVice","担保合同信息副表");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='抵押表';
            this.put("BLZL","办理资料");
            this.put("YWLSH","业务流水号");
            this.put("ZYWJZ","质押物价值");
            this.put("ZYWMC","质押物名称");
            this.put("ZYWSYQRLXDH","质押物所有权人联系电话");
            this.put("ZYWSYQRSFZHM","质押物所有权人身份证号码");
            this.put("ZYWSYQRXM","质押物所有权人姓名");
            this.put("guarantee_pledge_extenstions","质押表");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='质押表';
            this.put("ZYWJZ","质押物所有权人姓名");
            this.put("ZYWMC","质押物所有权人姓名");
            this.put("ZYWSYQRLXDH","质押物所有权人姓名");
            this.put("ZYWSYQRSFZHM","质押物所有权人姓名");
            this.put("ZYWSYQRXM","质押物所有权人姓名");
            this.put("guaranteePledgeVices","质押副表");
            this.put("cLoanHousingGuaranteeContractVice","担保合同信息副表");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='质押表';
            this.put("BZFLX","保证方类型（0：个人 1：机构）");
            this.put("FRDBLXDH","法人代表联系电话");
            this.put("FRDBSFZHM","法人代表身份证号码");
            this.put("FRDBXJZDZ","法人代表现居住地址");
            this.put("FRDBXM","法人代表姓名");
            this.put("TXDZ","通讯地址");
            this.put("YZBM","邮政编码");
            this.put("guaranteeVices","保证副表");
            this.put("cLoanHousingGuaranteeContractVice","担保合同信息副表");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='保证表';
            this.put("BLZL","办理资料");
            this.put("FWJG","房屋结构（0：框架 1：砖混 2：其他）");
            this.put("FWXZ","房屋性质（0：商品房 1：障碍性住房 2：自建房 3：两限房 4：集资房 5：危改房 6：经济适用房 7：房改房 8：其他）");
            this.put("FWZL","房屋坐落");
            this.put("GRSKYHZH","个人收款银行账号");
            this.put("GRSYZJ","个人使用资金");
            this.put("JCHJZMJ","建成后建造面积");
            this.put("JHJGRQ","计划竣工日期");
            this.put("JHJZFY","计划建造费用");
            this.put("JHKGRQ","计划开工日期");
            this.put("JSGCSGXKZH","建设工程施工许可证号");
            this.put("JZCS","建造层数");
            this.put("JZGCGHXKZH","建造工程规划许可证号");
            this.put("JZYDGHXKZH","建造用地规划许可证号");
            this.put("KHHYHMC","开户行银行名称");
            this.put("PZJGWH","批准机关文号");
            this.put("TDSYZH","项目编号");
            this.put("YHKHM","银行开户名");
            this.put("cLoanHousingPersonInformationBasic","贷款个人信息基础表");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='基础-房屋自建、翻修信息表';
            this.put("BLZL","办理资料");
            this.put("FWJG","房屋结构（0：框架 1：砖混 2：其他）");
            this.put("FWXZ","房屋性质（0：商品房 1：障碍性住房 2：自建房 3：两限房 4：集资房 5：危改房 6：经济适用房 7：房改房 8：其他）");
            this.put("FWZL","房屋坐落");
            this.put("GRSKYHZH","个人收款银行账号");
            this.put("GRSYZJ","个人使用资金");
            this.put("JCHJZMJ","建成后建造面积");
            this.put("JHJGRQ","计划竣工日期");
            this.put("JHJZFY","计划建造费用");
            this.put("JHKGRQ","计划开工日期");
            this.put("JSGCSGXKZH","建设工程施工许可证号");
            this.put("JZCS","建造层数");
            this.put("JZGCGHXKZH","建造工程规划许可证号");
            this.put("JZYDGHXKZH","建造用地规划许可证号");
            this.put("KHHYHMC","开户行银行名称");
            this.put("PZJGWH","批准机关文号");
            this.put("TDSYZH","土地使用证号");
            this.put("YHKHM","银行开户名");
            this.put("GRYWMX","个人业务明细");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='房屋自建、翻修信息表';
            this.put("BLZL","办理资料");
            this.put("DXGCYS","大修工程预算");
            this.put("FWZJBGJGMCJBH","房屋质检报告机关名称及编号");
            this.put("FWZL","房屋坐落");
            this.put("GRSKYHZH","个人收款银行账号");
            this.put("JHJGRQ","计划竣工日期");
            this.put("JHKGRQ","计划开工日期");
            this.put("KHYHMC","开户银行名称");
            this.put("TDSYZH","土地使用证号");
            this.put("YBDCZH","原不动产证号");
            this.put("YHKHM","银行开户名");
            this.put("YJZMJ","原建筑面积");
            this.put("cLoanHousingPersonInformationBasic","贷款个人信息基础表");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='基础-房屋大修信息表';
            this.put("BLZL","办理资料");
            this.put("DXGCYS","大修工程预算");
            this.put("FWZJBGJGMCJBH","房屋质检报告机关名称及编号");
            this.put("FWZL","房屋坐落");
            this.put("GRSKYHZH","个人收款银行账号");
            this.put("JHJGRQ","计划竣工日期");
            this.put("JHKGRQ","计划开工日期");
            this.put("KHYHMC","开户银行名称");
            this.put("TDSYZH","土地使用证号");
            this.put("YBDCZH","原不动产证号");
            this.put("YHKHM","银行开户名");
            this.put("YJZMJ","原建筑面积");
            this.put("GRYWMX","个人业务明细");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='房屋大修信息表';
            this.put("BLZL","办理资料");
            this.put("DanJia","单价");
            this.put("FWJG","房屋结构（0：框架 1：砖混 2：其他）");
            this.put("FWJGRQ","房屋竣工日期");
            this.put("FWJZMJ","房屋建筑面积");
            this.put("FWTNMJ","房屋套内面积");
            this.put("FWXS","房屋形式（0：在建房  1：现房）");
            this.put("FWXZ","房屋性质（0：商品房 1：障碍性住房 2：自建房 3：两限房 4：集资房 5：危改房 6：经济适用房 7：房改房 8：其他）");
            this.put("FWZJ","房屋总价");
            this.put("FWZL","房屋坐落");
            this.put("GFHTBH","购房合同编号");
            this.put("GRSKYHZH","个人收款银行账号");
            this.put("HTJE","合同金额");
            this.put("KHYHMC","开户银行名称");
            this.put("LPMC","楼盘名称");
            this.put("LXFS","联系方式");
            this.put("SFK","首付款");
            this.put("SFRKHYHMC","售房人开户银行名称");
            this.put("SFRMC","售房人名称");
            this.put("SFRYHKHM","售房人银行开户名");
            this.put("SFRZHHM","售房人账户号码");
            this.put("SFWESF","是否为二手房（0：否 1：是）");
            this.put("SPFYSXKBH","商品房预售许可编号");
            this.put("YFK","已付款");
            this.put("YHKHM","银行开户名");
            this.put("cLoanHousingPersonInformationBasic","贷款个人信息基础表");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='基础-房屋购买信息表';
            this.put("BLZL","办理资料");
            this.put("DanJia","单价");
            this.put("FWJG","房屋结构（0：框架 1：砖混 2：其他）");
            this.put("FWJGRQ","房屋竣工日期");
            this.put("FWJZMJ","房屋建筑面积");
            this.put("FWTNMJ","房屋套内面积");
            this.put("FWXS","房屋形式（0：在建房  1：现房）");
            this.put("FWXZ","房屋性质（0：商品房 1：障碍性住房 2：自建房 3：两限房 4：集资房 5：危改房 6：经济适用房 7：房改房 8：其他）");
            this.put("FWZJ","房屋总价");
            this.put("FWZL","房屋坐落");
            this.put("GFHTBH","购房合同编号");
            this.put("GRSKYHZH","个人收款银行账号");
            this.put("HTJE","合同金额");
            this.put("KHYHMC","开户银行名称");
            this.put("LPMC","楼盘名称");
            this.put("LXFS","联系方式");
            this.put("SFK","首付款");
            this.put("SFRKHYHMC","售房人开户银行名称");
            this.put("SFRMC","售房人名称");
            this.put("SFRYHKHM","售房人银行开户名");
            this.put("SFRZHHM","售房人账户号码");
            this.put("SFWESF","是否为二手房（0：否 1：是）");
            this.put("SPFYSXKBH","商品房预售许可编号");
            this.put("YFK","已付款");
            this.put("YHKHM","银行开户名");
            this.put("GRYWMX","个人业务明细");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='房屋购买信息副表';
            this.put("BJSJ","办结时间");
            this.put("BLSJ","办理时间");
            this.put("BLZL","办理资料");
            this.put("CZNR","操作内容");
            this.put("CZQD","操作渠道");
            this.put("CZY","操作员");
            this.put("DDSJ","到达时间");
            this.put("DKDBLX","贷款担保类型");
            this.put("DKYT","贷款用途");
            this.put("DKZH","贷款账号");
            this.put("SHSJ","审核时间（审核通过/不通过时的时间");
            this.put("SHYBH","审核员编号");
            this.put("STEP","状态机状态");
            this.put("YWLSH","业务流水号");
            this.put("YWWD","业务网点");
            this.put("loanContract","个人住房贷款借款合同信息");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='个人贷款-业务流程表';
            this.put("BLZL","办理资料");
            this.put("DWDH","单位电话");
            this.put("DWDZ","单位地址");
            this.put("DWMC","单位名称");
            this.put("DWXZ","单位性质");
            this.put("DWZH","单位账号");
            this.put("GRJCJS","个人缴存基数");
            this.put("GRZHYE","个人账户余额");
            this.put("GRZHZT","个人账户状态");
            this.put("HKSZD","户口所在地");
            this.put("JCD","缴存地");
            this.put("JZNY","缴至年月");
            this.put("LXZCJCYS","连续正常缴存月数");
            this.put("YJCE","月缴存额");
            this.put("YWLSH","业务流水号");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='共同借款人拓展表';
            this.put("BLZL","办理资料");
            this.put("CDGX","参贷关系");
            this.put("DWDH","单位电话");
            this.put("DWDZ","单位地址");
            this.put("DWMC","单位名称");
            this.put("DWXZ","单位性质");
            this.put("DWZH","单位账号");
            this.put("GDDHHM","固定电话号码");
            this.put("GRJCJS","个人缴存基数");
            this.put("GRZHYE","个人账户余额");
            this.put("GRZHZT","个人账户状态");
            this.put("GTJKRGJJZH","共合借款人公积金账号");
            this.put("GTJKRXM","共同借款人姓名");
            this.put("GTJKRZJHM","共同借款人证件号码");
            this.put("GTJKRZJLX","共同借款人证件类型");
            this.put("HKSZD","户口所在地");
            this.put("JCD","缴存地");
            this.put("JKHTBH","借款合同编号");
            this.put("JZNY","缴至年月");
            this.put("LXZCJCYS","连续正常缴存月数");
            this.put("SJHM","手机号码");
            this.put("YJCE","月缴存额");
            this.put("YSR","月收入");
            this.put("GRYWMX","个人业务明细");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='贷款申请-共同借款人信息表';
            this.put("BeiZhu","备注");
            this.put("BLZL","办理资料");
            this.put("BZJKHM","保证金开户名");
            this.put("BZJZH","保证金账户");
            this.put("BZJZHKHH","保证金账户开户行");
            this.put("CZY","操作员");
            this.put("DWDZ","单位地址");
            this.put("FKGS","房开公司");
            this.put("FKGSZH","房开公司账号");
            this.put("FRDB","法人代表");
            this.put("FRDBZJHM","法人代表证件号码");
            this.put("FRDBZJLX","法人代表证件类型（0：身份证 1：军官证 2：护照 3：外国人永久居留证 4：其他）");
            this.put("LXDH","联系电话");
            this.put("LXR","联系人");
            this.put("SFBG","是否变更");
            this.put("SFQY","是否启用");
            this.put("SJFLB","售建房类别（0：开发商 1：个人 2：其他）");
            this.put("YWWD","业务网点");
            this.put("ZCDZ","注册地址");
            this.put("ZCZJ","注册资金");
            this.put("ZZDJ","资质等级（0：一级 1：二级 2：三级 3：四级）");
            this.put("ZZJGDM","组织机构代码");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='房开公司基础表';
            this.put("SFRKHYHKHM","售房人开户银行开户名");
            this.put("SFRKHYHMC","售房人开户银行名称");
            this.put("SFRZHHM","售房人账户号码");
            this.put("FKGSZB","房开公司主表");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='房开公司拓展主表';
            this.put("BeiZhu","备注");
            this.put("BLZL","办理资料");
            this.put("BZJKHM","保证金开户名");
            this.put("BZJZH","保证金账户");
            this.put("BZJZHKHH","保证金账户开户行");
            this.put("DWDZ","单位地址");
            this.put("FKGS","房开公司");
            this.put("FKGSZH","房开公司账号");
            this.put("FRDB","法人代表");
            this.put("FRDBZJHM","法人代表证件号码");
            this.put("FRDBZJLX","法人代表证件类型（0：身份证 1：军官证 2：护照 3：外国人永久居留证 4：其他）");
            this.put("LXDH","联系电话");
            this.put("LXR","联系人");
            this.put("SFBG","是否变更");
            this.put("SJFLB","售建房类别（0：开发商 1：个人 2：其他）");
            this.put("ZCDZ","注册地址");
            this.put("ZCZJ","注册资金");
            this.put("ZZDJ","资质等级（0：一级 1：二级 2：三级 3：四级）");
            this.put("ZZJGDM","组织机构代码");
            this.put("GRYWMX","个人业务明细");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='房开公司副表';
            this.put("SFRKHYHKHM","售房人开户银行开户名");
            this.put("SFRKHYHMC","售房人开户银行名称");
            this.put("SFRZHHM","售房人账户号码");
            this.put("FKGSFB","房开公司副表");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='房开公司拓展副表';
            this.put("BLZL","办理资料");
            this.put("BZHTBH","保证合同编号");
            this.put("BZJGMC","保证机构名称");
            this.put("DBHTBH","担保合同编号");
            this.put("DBJGMC","担保机构名称");
            this.put("DKBZJ","贷款保证金");
            this.put("DKDBLX","贷款担保类型");
            this.put("DYQJCRQ","抵押物解除日期");
            this.put("DYQJLRQ","抵押权简历日期");
            this.put("DYWFWZL","抵押物房屋坐落");
            this.put("DYWPGJZ","抵押物评估价值");
            this.put("DYWQZH","抵押物权证号");
            this.put("DYWTXQZH","抵押物他项权证号");
            this.put("FHBZJRQ","返还保证金日期 YYYYMMDD");
            this.put("JKHTBH","借款合同编号");
            this.put("ZYHTBH","质押合同编号");
            this.put("ZYHTJSRQ","质押合同结束日期 YYYYMMDD");
            this.put("ZYHTKSRQ","质押合同开始日期 YYYYMMDD");
            this.put("ZYWBH","质押物编号");
            this.put("ZYWJZ","质押物价值");
            this.put("ZYWMC","质押物名称");
            this.put("GRYWMX","个人业务明细");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='担保合同信息副表';
            this.put("CZY","操作员");
            this.put("DKFFE","贷款发放额");
            this.put("DKFFRQ","贷款发放日期");
            this.put("DKZH","贷款账号");
            this.put("FKYHMC","放款银行名称");
            this.put("FKZH","放款账户");
            this.put("FKZHHM","放款账户户名");
            this.put("JKHTBH","借款合同编号");
            this.put("JKRXM","借款人姓名");
            this.put("JKRZJHM","借款人证件号码");
            this.put("JKRZJLX","借款人证件类型");
            this.put("SKYHMC","收款银行名称");
            this.put("SKZH","收款账户");
            this.put("SKZHHM","收款账户户名");
            this.put("state","状态（0、待入账，1、已入账）");
            this.put("YWLSH","业务流水号");
            this.put("YWWD","业务网点");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='放款记录表';
            this.put("DKZH","贷款账号");
            this.put("HKQC","还款期次");
            this.put("SFHK","是否还款（0：否 1：是）");
            this.put("SSRQ","实收日期");
            this.put("SSYQBJJE","实收逾期本金金额");
            this.put("SSYQFXJE","实收逾期罚息金额");
            this.put("SSYQLXJE","实收逾期利息金额");
            this.put("YQBJ","逾期本金");
            this.put("YQFX","逾期罚息");
            this.put("YQLX","逾期利息");
            this.put("YQQC","逾期期次");
            this.put("YWLSH","业务流水号");
            this.put("grywmx","还款申请表");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='还款-逾期信息表';
            this.put("BLZL","办理资料");
            this.put("CSNY","出生年月");
            this.put("CZY","操作员");
            this.put("DKYT","贷款用途");
            this.put("DKZH","贷款账号");
            this.put("DKZHZT","贷款账户状态");
            this.put("DQYQQS","当前逾期期数");
            this.put("DWDH","单位电话");
            this.put("DWDZ","单位地址");
            this.put("DWMC","单位名称");
            this.put("DWXZ","单位性质");
            this.put("DWZH","单位账号");
            this.put("GDDHHM","固定电话号码");
            this.put("GRJCJS","个人缴存基数");
            this.put("GRZHYE","个人账户余额");
            this.put("GRZHZT","个人账户状态");
            this.put("HKSZD","户口所在地");
            this.put("HYZK","婚姻状态（0：已婚 1：未婚 2：丧偶 3：离婚 4：未说明的婚姻状况）");
            this.put("JCD","缴存地");
            this.put("JKRGJJZH","借款人公积金账号");
            this.put("JKRXM","借款人姓名");
            this.put("JKRZJHM","借款人证件号码");
            this.put("JKRZJLX","借款人证件类型");
            this.put("JKZK","健康状态（0：良好 1：一般 2：差）");
            this.put("JTYSR","家庭月收入");
            this.put("JTZZ","家庭住址");
            this.put("JZNY","缴至年月");
            this.put("LXZCJCYS","连续正常缴存月数");
            this.put("NianLing","年龄");
            this.put("QTBLZL","其他办理资料");
            this.put("SJHM","手机号码");
            this.put("SPBWJ","审批表文件");
            this.put("XingBie","性别");
            this.put("XueLi","学历");
            this.put("YGXZ","用工性质（0：正式职工 1：合同制 2：聘用制）");
            this.put("YHQS","已还期数");
            this.put("YJCE","月缴存额");
            this.put("YSR","月收入");
            this.put("YWLSH","业务流水号");
            this.put("YWWD","业务网点");
            this.put("ZhiCheng","职称");
            this.put("ZhiWu","职务");
            this.put("ZYJJLY","主要经济来源（0：工资收入 1：个体经营收入 2：其他非工资收入）");
            this.put("coborrower","共同还款人");
            this.put("guaranteeContract","担保合同");
            this.put("loanContract","借款合同");
            this.put("personalAccount","贷款账户信息");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='贷款个人信息基础表';
            this.put("BLZL","办理资料");
            this.put("CSNY","出生年月");
            this.put("DKFFRQ","贷款发放日期");
            this.put("DWDH","单位电话");
            this.put("DWDZ","单位地址");
            this.put("DWMC","单位名称");
            this.put("DWXZ","单位性质");
            this.put("DWZH","单位账号");
            this.put("FKYHMC","放款银行名称 （0：建设银行 1：中国银行 2：交通银行 3：农业银行 4：工商银行）");
            this.put("GDDHHM","固定电话号码");
            this.put("GRJCJS","个人缴存基数");
            this.put("GRZHYE","个人账户余额");
            this.put("GRZHZT","个人账户状态");
            this.put("HKSZD","户口所在地");
            this.put("HYZK","婚姻状态（0：已婚 1：未婚 2：丧偶 3：离婚 4：未说明的婚姻状况）");
            this.put("JCD","缴存地");
            this.put("JKHTBH","借款合同编号");
            this.put("JKRGJJZH","借款人公积金账号");
            this.put("JKRXM","借款人姓名");
            this.put("JKRZJHM","借款人证件号码");
            this.put("JKRZJLX","借款人证件类型");
            this.put("JKZK","健康状态（0：良好 1：一般 2：差）");
            this.put("JTYSR","家庭月收入");
            this.put("JTZZ","家庭住址");
            this.put("JZNY","缴至年月");
            this.put("LXZCJCYS","连续正常缴存月数");
            this.put("NianLing","年龄");
            this.put("QTBLZL","其他办理资料");
            this.put("SJHM","手机号码");
            this.put("SPBWJ","审批表文件");
            this.put("XingBie","性别");
            this.put("XueLi","学历");
            this.put("YGXZ","用工性质（0：正式职工 1：合同制 2：聘用制）");
            this.put("YJCE","月缴存额");
            this.put("YSR","月收入");
            this.put("ZhiCheng","职称");
            this.put("ZhiWu","职务");
            this.put("ZYJJLY","主要经济来源（0：工资收入 1：个体经营收入 2：其他非工资收入）");
            this.put("GRYWMX","个人业务明细");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='个人信息副表';
            this.put("DKGBJHQS","贷款改变计划期数");
            this.put("DKGBJHYE","贷款改变计划余额");
            this.put("DKXFFRQ","贷款新发放日期");
            this.put("DQQC","当期期次");
            this.put("TQHKSJ","提前还款时间");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='个人贷款账号拓展';
            this.put("DKHTWJ","贷款合同文件");
            this.put("DKYT","贷款用途");
            this.put("GRSKYHZH","个人收款银行账号");
            this.put("GRSYZJ","个人使用资金");
            this.put("JHFXFY","计划翻修费用");
            this.put("JHJZZJ","计划建造总价");
            this.put("KHHM","开户户名");
            this.put("KHYHMC","开户银行名称");
            this.put("SJHM","手机号码");
            this.put("YJKHTBH","原借款合同编号");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='个人贷款合同拓展';
            this.put("module_id","模块ID");
            this.put("permission_code","权限代码");
            this.put("permission_name","权限名称");
            this.put("permission_note","权限备注");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='权限表';
            this.put("role_name","角色名称");
            this.put("role_note","角色备注");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='角色表';
            this.put("SFYSY","是否已使用");
            this.put("status","0 : 正常， 1 : 销户");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='银行专户信息 扩展表';
            this.put("EVENT","触发事件");
            this.put("FLAG","是否启用");
            this.put("IsAudit","是否是审核流程");
            this.put("ROLE","操作人员");
            this.put("SOURCE","源状态");
            this.put("SUB_TYPE","业务子类型");
            this.put("TARGET","目标状态");
            this.put("TransitionKind","状态转移类型");
            this.put("TYPE","业务所属类型");
            this.put("WORKSTATION","业务网点");
            this.put("effectiveDate","生效时间");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='业务状态机配置表';
            this.put("STEP","状态机步骤");
            this.put("YWZT","业务状态");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='业务状态机步骤类型';
            this.put("modle","模块名称（01：归集 02：提取 03：贷款）");
            this.put("business","业务名称（01：单位缴存登记和建账 02：单位缴存登记信息变更 03：缴存0余额单位登记注销 04：单位缴存比例调整 05：个人账户设立（灵活个人属于单位经办人） 06：个人信息变更 07：同城转移合户，账户信息不完善的情况下 08：封、启存 09：异地转移接续（非核心）） 10：申请缓停缴 11：系统催缴 12：个人、单位（解）冻结 01：未提取的多缴错缴 02：人事类个人提取 03：提取公积金归还住房贷款 04：购、建、租房提取 05：其他、原始提取 06：职工本人办理公积金抵押贷款 07：房开商协助办理贷款 01：借款人信息 02：共同借款人（配偶）信息 03：购买商品房 04：购买二手房 05：自建、翻修 06：大修 07：担保信息 08：其他资料");
            this.put("certificateName","资料名称");
            this.put("required","是否必须（0：是 1：否）");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='上传资料设置表';
            this.put("DWYJCE","单位月缴存额");
            this.put("GRCKZHHM","个人存款账户号码");
            this.put("GRCKZHKHYHDM","个人存款账户开户银行代码");
            this.put("GRCKZHKHYHMC","个人存款账户开户银行名称");
            this.put("GRJCJS","个人缴存基数");
            this.put("GRYJCE","个人月缴存额");
            this.put("GRZH","个人账号");
            this.put("GRZHDNGJYE","个人账户当年归集余额");
            this.put("GRZHSNJZYE","个人账户上年结转余额");
            this.put("GRZHYE","个人账户余额");
            this.put("GRZHZT","个人账户状态");
            this.put("KHRQ","开户日期");
            this.put("XHRQ","销户日期");
            this.put("XHYY","销户原因");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='个人账户信息 表5.0.4';
            this.put("CZBZ","冲账标识");
            this.put("DNGJFSE","当年归集发生额");
            this.put("FSE","发生额");
            this.put("FSLXE","发生利息额");
            this.put("GJHTQYWLX","归集和提取业务类型");
            this.put("GRZH","个人账号");
            this.put("JZRQ","记账日期");
            this.put("SNJZFSE","上年结转发生额");
            this.put("TQFS","提取方式");
            this.put("TQYY","提取原因");
            this.put("YWLSH","业务流水号");
            this.put("extension","个人业务明细扩展");
            this.put("Person","个人信息");
            this.put("Unit","单位信息");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='个人业务明细信息 表5.0.5';
            this.put("DWFCRS","单位封存人数");
            this.put("DWJCBL","单位缴存比例");
            this.put("DWJCRS","单位缴存人数");
            this.put("DWXHRQ","单位销户日期");
            this.put("DWXHYY","单位销户原因");
            this.put("DWZH","单位账号");
            this.put("DWZHYE","单位账户余额");
            this.put("DWZHZT","单位账户状态");
            this.put("GRJCBL","个人缴存比例");
            this.put("JZNY","缴至年月");
            this.put("extenstion","缴存单位账号扩展");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='单位账户信息 表5.0.2';
            this.put("CZBZ","冲账标识");
            this.put("DWZH","单位账号");
            this.put("FSE","发生额");
            this.put("FSLXE","发生利息额");
            this.put("FSRS","发生人数");
            this.put("HBJNY","汇补缴年月");
            this.put("JZRQ","记账日期");
            this.put("YWLSH","业务流水号");
            this.put("YWMXLX","业务明细类型");
            this.put("extenstion","缴存单位业务明细扩展");
            this.put("Unit","单位信息");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='单位业务明细信息 表5.0.3';
            this.put("CSNY","出生年月");
            this.put("GDDHHM","固定电话号码");
            this.put("GRZH","个人账号");
            this.put("HYZK","婚姻状况");
            this.put("JTYSR","家庭月收入");
            this.put("JTZZ","家庭住址");
            this.put("SJHM","手机号码");
            this.put("XingBie","性别");
            this.put("XingMing","姓名");
            this.put("XMQP","姓名全拼");
            this.put("XueLi","学历");
            this.put("YZBM","邮政编码");
            this.put("ZhiChen","职称");
            this.put("ZhiWu","职务");
            this.put("ZhiYe","职业");
            this.put("ZJHM","证件号码");
            this.put("ZJLX","证件类型");
            this.put("extension","个人基础信息扩展");
            this.put("PersonalAccount","个人账户信息");
            this.put("Unit","单位基础信息");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='个人信息 表4.0.3';
            this.put("DWJCBLSX","单位缴存比例上限");
            this.put("DWJCBLXX","单位缴存比例下限");
            this.put("GRJCBLSX","个人缴存比例上限");
            this.put("GRJCBLXX","个人缴存比例下限");
            this.put("GRZFDKZCNX","个人住房贷款最长年限");
            this.put("GRZFDKZGDKBL","个人住房贷款最高贷款比例");
            this.put("GRZFDKZGED","个人住房贷款最高额度");
            this.put("LLLX","利率类型");
            this.put("XMDKZCNX","项目贷款最长年限");
            this.put("XMDKZGDKBL","项目贷款最高贷款比例");
            this.put("YJCESX","月缴存额上限");
            this.put("YJCEXX","月缴存额下限");
            this.put("ZXLL","执行利率");
            this.put("extension","政策信息 扩展表");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='政策信息 表4.0.4';
            this.put("DWDZ","单位地址");
            this.put("DWDZXX","单位电子信箱");
            this.put("DWFRDBXM","单位法人代表姓名");
            this.put("DWFRDBZJHM","单位法人代表证件号码");
            this.put("DWFRDBZJLX","单位法人代表证件类型");
            this.put("DWFXR","单位发薪日");
            this.put("DWJJLX","单位经济类型");
            this.put("DWKHRQ","单位开户日期");
            this.put("DWLSGX","单位隶属关系");
            this.put("DWMC","单位名称");
            this.put("DWSLRQ","单位设立日期");
            this.put("DWSSHY","单位所属行业");
            this.put("DWYB","单位邮编");
            this.put("DWZH","单位账号");
            this.put("JBRGDDHHM","经办人固定电话号码");
            this.put("JBRSJHM","经办人手机号码");
            this.put("JBRXM","经办人姓名");
            this.put("JBRZJHM","经办人证件号码");
            this.put("JBRZJLX","经办人证件类型");
            this.put("STYHDM","受托银行代码");
            this.put("STYHMC","受托银行名称");
            this.put("ZZJGDM","组织机构代码");
            this.put("extension","缴存单位基础信息扩展");
            this.put("CollectionUnitAccount","单位账户");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='缴存单位信息 表4.0.2';
            this.put("CNLSH","出纳流水号");
            this.put("CZBS","冲账标识");
            this.put("DFFSE","贷方发生额");
            this.put("JFFSE","借方发生额");
            this.put("JZPZH","记账凭证号");
            this.put("JZRQ","记账日期");
            this.put("PZSSNY","凭证所属年月");
            this.put("RZRQ","入账日期");
            this.put("RZZT","入账状态");
            this.put("YEJDFX","余额借贷方向");
            this.put("YHJSLSH","银行结算流水号");
            this.put("YHZHHM","银行专户号码");
            this.put("YuE","余额");
            this.put("ZhaiYao","摘要");
            this.put("ZJYWLX","资金业务类型");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='银行存款日记账信息 表8.0.6';
            this.put("DFFSE","贷方发生额");
            this.put("JFFSE","借方发生额");
            this.put("JZRQ","记账日期");
            this.put("KMBH","科目编号");
            this.put("KMMC","科目名称");
            this.put("QCYE","期初余额");
            this.put("QCYEFX","期初余额方向");
            this.put("QMYE","期末余额");
            this.put("QMYEFX","期末余额方向");
            this.put("ZhaiYao","摘要");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='总账信息 表8.0.3';
            this.put("DFBJ","兑付本金");
            this.put("DFRQ","兑付日期");
            this.put("DQRQ","到期日期");
            this.put("GMJE","购买金额");
            this.put("GMQD","购买渠道");
            this.put("GMRQ","购买日期");
            this.put("GZBH","国债编号");
            this.put("GZMC","国债名称");
            this.put("GZPZH","国债凭证号");
            this.put("GZZL","国债种类");
            this.put("LiLv","利率");
            this.put("LXSR","利息收入");
            this.put("MianZhi","面值");
            this.put("QiXian","期限");
            this.put("QXRQ","起息日期");
            this.put("ShuLiang","数量");
            this.put("STYHDM","受托银行代码");
            this.put("YHZHHM","银行专户号码");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='国债明细信息 表8.0.8';
            this.put("DFFSE","贷方发生额");
            this.put("FJDJS","附件单据数");
            this.put("JFFSE","借方发生额");
            this.put("JZPZH","记账凭证号");
            this.put("JZRQ","记账日期");
            this.put("KMBH","科目编号");
            this.put("ZhaiYao","摘要");
            this.put("extension","记账凭证信息 扩展");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='记账凭证信息 表8.0.5';
            this.put("KMBH","科目编号");
            this.put("KMJB","科目级别");
            this.put("KMMC","科目名称");
            this.put("KMSX","科目属性");
            this.put("KMYEFX","科目余额方向");
            this.put("extension","科目信息扩展");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='科目信息 表8.0.2';
            this.put("DFFSE","贷方发生额");
            this.put("JFFSE","借方发生额");
            this.put("JZPZH","记账凭证号");
            this.put("JZRQ","记账日期");
            this.put("KMBH","科目编号");
            this.put("QCYE","期初余额");
            this.put("QCYEFX","期初余额方向");
            this.put("QMYE","期末余额");
            this.put("QMYEFX","期末余额方向");
            this.put("ZhaiYao","摘要");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='明细账信息 表 8.0.4';
            this.put("BJJE","本金金额");
            this.put("CKQX","存款期限");
            this.put("CRRQ","存入日期");
            this.put("DQCKBH","定期存款编号");
            this.put("DQRQ","到期日期");
            this.put("KHYHMC","开户银行名称");
            this.put("LiLv","利率");
            this.put("LXSR","利息收入");
            this.put("QKRQ","取款日期");
            this.put("ZHHM","专户号码");
            this.put("ZHMC","账户名称");
            this.put("ZQQK","支取情况");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='定期存款明细信息 表 8.0.7';
            this.put("BJJE","本金金额");
            this.put("DKYHDM","贷款银行代码");
            this.put("DKYWMXLX","贷款业务明细类型");
            this.put("DKZH","贷款账号");
            this.put("DQQC","当期期次");
            this.put("FSE","发生额");
            this.put("FXJE","罚息金额");
            this.put("JZRQ","记账日期");
            this.put("LXJE","利息金额");
            this.put("YQZZCBJJE","逾期转正常本金金额");
            this.put("YWFSRQ","业务发生日期");
            this.put("YWLSH","业务流水号");
            this.put("ZCZYQBJJE","正常转逾期本金金额");
            this.put("extenstion","个人贷款合同拓展");
            this.put("grywmx","还款业务副表");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='个人住房贷款业务明细信息 表6.0.6';
            this.put("CDGX","参贷关系");
            this.put("GDDHHM","固定电话号码");
            this.put("GTJKRGJJZH","共同借款人公积金账号");
            this.put("GTJKRXM","共同借款人姓名");
            this.put("GTJKRZJHM","共同借款人证件号码");
            this.put("GTJKRZJLX","共同借款人证件类型");
            this.put("JKHTBH","借款合同编号");
            this.put("SJHM","手机号码");
            this.put("YSR","月收入");
            this.put("extenstion","共同借款人拓展表");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='共同借款人信息 表6.0.4';
            this.put("BZHTBH","保证合同编号");
            this.put("BZJGMC","保证机构名称");
            this.put("DBHTBH","担保合同编号");
            this.put("DBJGMC","担保机构名称");
            this.put("DKBZJ","贷款保证金");
            this.put("DKDBLX","贷款担保类型");
            this.put("DYQJCRQ","抵押权解除日期");
            this.put("DYQJLRQ","抵押权建立日期");
            this.put("DYWFWZL","抵押物房屋坐落");
            this.put("DYWPGJZ","抵押物评估价值");
            this.put("DYWQZH","抵押物权证号");
            this.put("DYWTXQZH","抵押物他项权证号");
            this.put("FHBZJRQ","返还保证金日期");
            this.put("JKHTBH","借款合同编号");
            this.put("ZYHTBH","质押合同编号");
            this.put("ZYHTJSRQ","质押合同结束日期");
            this.put("ZYHTKSRQ","质押合同开始日期");
            this.put("ZYWBH","质押物编号");
            this.put("ZYWJZ","质押物价值");
            this.put("ZYWMC","质押物名称");
            this.put("extension","担保合同基础拓展表");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='担保合同信息 表6.0.3';
            this.put("DKZH","贷款账号");
            this.put("HKQC","还款期次");
            this.put("SSRQ","实收日期");
            this.put("SSYQBJJE","实收逾期本金金额");
            this.put("SSYQFXJE","实收逾期罚息金额");
            this.put("SSYQLXJE","实收逾期利息金额");
            this.put("YQBJ","逾期本金");
            this.put("YQFX","逾期罚息");
            this.put("YQLX","逾期利息");
            this.put("YQQC","逾期期次");
            this.put("extenstion","逾期还款拓展");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='个人住房贷款逾期登记信息 表6.0.7';
            this.put("DKFFE","贷款发放额");
            this.put("DKFFRQ","贷款发放日期");
            this.put("DKFXDJ","贷款风险等级 ");
            this.put("DKJQRQ","贷款结清日期");
            this.put("DKLL","贷款利率");
            this.put("DKQS","贷款期数");
            this.put("DKYE","贷款余额");
            this.put("DKZH","贷款账号");
            this.put("DQJHGHBJ","当期计划归还本金");
            this.put("DQJHGHLX","当期计划归还利息");
            this.put("DQJHHKJE","当期计划还款金额");
            this.put("DQYHBJ","当前应还本金");
            this.put("DQYHFX","当前应还罚息");
            this.put("DQYHJE","当前应还金额");
            this.put("DQYHLX","当前应还利息");
            this.put("FXZE","罚息总额");
            this.put("HSBJZE","回收本金总额");
            this.put("HSLXZE","回收利息总额");
            this.put("JKHTBH","借款合同编号");
            this.put("LJYQQS","累计逾期期数");
            this.put("LLFDBL","利率浮动比例");
            this.put("TQGHBJZE","提前归还本金总额");
            this.put("YQBJZE","逾期本金总额");
            this.put("YQLXZE","逾期利息总额");
            this.put("extenstion","个人贷款账户拓展");
            this.put("contract","个人住房贷款借款合同信息");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='个人住房贷款账户信息 表6.0.5';
            this.put("DKDBLX","贷款担保类型");
            this.put("DKHKFS","贷款还款方式");
            this.put("DKLX","贷款类型");
            this.put("DKQS","贷款期数");
            this.put("FWJZMJ","房屋建筑面积");
            this.put("FWTNMJ","房屋套内面积");
            this.put("FWXZ","房屋性质");
            this.put("FWZJ","房屋总价");
            this.put("FWZL","房屋坐落");
            this.put("GFHTBH","购房合同编号");
            this.put("GFSFK","购房首付款");
            this.put("HKZH","还款账号");
            this.put("HTDKJE","合同贷款金额");
            this.put("JKHTBH","借款合同编号");
            this.put("JKHTLL","借款合同利率");
            this.put("JKHTQDRQ","借款合同签订日期");
            this.put("JKRGJJZH","借款人公积金账号");
            this.put("JKRXM","借款人姓名");
            this.put("JKRZJH","借款人证件号");
            this.put("JKRZJLX","借款人证件类型");
            this.put("LLFDBL","利率浮动比例");
            this.put("SFRKHYHDM","售房人开户银行代码");
            this.put("SFRKHYHMC","售房人开户银行名称");
            this.put("SFRMC","售房人名称");
            this.put("SFRZHHM","售房人账户号码");
            this.put("SWTYHDM","受委托银行代码");
            this.put("SWTYHMC","受委托银行名称");
            this.put("YDDQRQ","约定到期日期");
            this.put("YDFKRQ","约定放款日期");
            this.put("YDHKR","约定还款日");
            this.put("ZHKHYHDM","账户开户银行代码");
            this.put("ZHKHYHMC","账户开户银行名称");
            this.put("extenstion","个人贷款合同拓展");
            this.put("BLZL","办理资料");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='个人住房贷款借款合同信息 表6.0.2';
            this.put("DFFSE","贷方发生额");
            this.put("JFFSE","借方发生额");
            this.put("JYDSZHHM","交易对手账户号码");
            this.put("JYDSZHMC","交易对手账户名称");
            this.put("JYDSZHYHDM","交易对手账户银行代码");
            this.put("JZRQ","记账日期");
            this.put("QCYEFX","期初余额方向");
            this.put("QMYEFX","期末余额方向");
            this.put("XMBH","项目编号");
            this.put("YWLSH","业务流水号");
            this.put("ZFYT","支付用途");
            this.put("ZJJGZHHM","资金监管账户号码");
            this.put("ZJJGZHQCYE","资金监管账户期初余额");
            this.put("ZJJGZHQMYE","资金监管账户期末余额");
            this.put("ZJLRLY","资金流入来源");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='资金封闭管理信息 表7.0.8';
            this.put("DKED","贷款额度");
            this.put("GYTDSYZH","国有土地使用证号");
            this.put("JSGCGHXKZH","建设工程规划许可证号");
            this.put("JSGM","建设规模");
            this.put("JSYDGHXKZH","建设用地规划许可证号");
            this.put("JZGCSGXKZH","建筑工程施工许可证号");
            this.put("LXPFWH","立项批复文号");
            this.put("SSCSDM","所属城市代码");
            this.put("TZGM","投资规模");
            this.put("XMBH","项目编号");
            this.put("XMFLJB","项目分类级别");
            this.put("XMLX","项目类型");
            this.put("XMMC","项目名称");
            this.put("XMPC","项目批次");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='建设项目信息 表7.0.2';
            this.put("DKFXDJ","贷款风险等级");
            this.put("DKJQRQ","贷款结清日期");
            this.put("DKLL","贷款利率");
            this.put("DKYE","贷款余额");
            this.put("DKZH","贷款账号");
            this.put("FXZE","罚息总额");
            this.put("HSBJZE","回收本金总额");
            this.put("HSLXZE","回收利息总额");
            this.put("JKHTBH","借款合同编号");
            this.put("NYFXLL","挪用罚息利率");
            this.put("TQHKBJZE","提前还款本金总额");
            this.put("YQBJ","逾期本金");
            this.put("YQFXLL","逾期罚息利率");
            this.put("YQLX","逾期利息");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='项目贷款账户信息 表7.0.5';
            this.put("DKFFFS","贷款发放方式");
            this.put("DKHBFS","贷款还本方式");
            this.put("DKJE","贷款金额");
            this.put("DKLL","贷款利率");
            this.put("DKQX","贷款期限");
            this.put("DKR","贷款人");
            this.put("DKRQYDB","贷款人签约代表");
            this.put("DKRQYSJ","贷款人签约时间");
            this.put("JKHTBH","借款合同编号");
            this.put("JKR","借款人");
            this.put("JKRQYDB","借款人签约代表");
            this.put("JKRQYSJ","借款人签约时间");
            this.put("NYFXLL","挪用罚息利率");
            this.put("WTR","委托人");
            this.put("WTRQYDB","委托人签约代表");
            this.put("WTRQYSJ","委托人签约时间");
            this.put("XMBH","项目编号");
            this.put("YHDM","银行代码");
            this.put("YQFXLL","逾期罚息利率");
            this.put("ZJJGZHHM","资金监管账户号码");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='项目贷款借款合同信息 表7.0.3';
            this.put("BJJE","本金金额");
            this.put("DKZH","贷款账号");
            this.put("FSE","发生额");
            this.put("JZRQ","记账日期");
            this.put("LXJE","利息金额");
            this.put("NYFXJE","挪用罚息金额");
            this.put("YQFXJE","逾期罚息金额");
            this.put("YWLSH","业务流水号");
            this.put("YWMXLX","业务明细类型");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='项目贷款业务明细信息 表7.0.6';
            this.put("DYHTBH","抵押合同编号");
            this.put("DYL","抵押率");
            this.put("DYQJCRQ","抵押权解除日期");
            this.put("DYQJLRQ","抵押权建立日期");
            this.put("DYWCS","抵押物处所");
            this.put("DYWLX","抵押物类型");
            this.put("DYWMC","抵押物名称");
            this.put("DYWPGJZ","抵押物评估价值");
            this.put("DYWQZH","抵押物权证号");
            this.put("JKHTBH","借款合同编号");
            this.put("YDYJZ","已抵押价值");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='项目贷款抵押合同信息 表7.0.4';
            this.put("DKZH","贷款账号");
            this.put("SSRQ","实收日期");
            this.put("SSYQBJ","实收逾期本金");
            this.put("SSYQFX","实收逾期罚息");
            this.put("SSYQLX","实收逾期利息");
            this.put("YQBJ","逾期本金");
            this.put("YQFX","逾期罚息");
            this.put("YQLX","逾期利息");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='项目贷款逾期登记信息 表7.0.7';
            this.put("FKYHDM","付款银行代码");
            this.put("FKZHHM","付款账户号码");
            this.put("FKZHMC","付款账户名称");
            this.put("FSE","发生额");
            this.put("JSFSRQ","结算发生日期");
            this.put("JSYHDM","结算银行代码");
            this.put("SKYHDM","收款银行代码");
            this.put("SKZHHM","收款账户号码");
            this.put("SKZHMC","收款账户名称");
            this.put("YHJSLSH","银行结算流水号");
            this.put("YWLSH","业务流水号");
            this.put("YWPZHM","业务凭证号码");
            this.put("ZhaiYao","摘要");
            this.put("ZJYWLX","资金业务类型");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='银行结算流水信息';
            this.put("KHRQ","开户日期");
            this.put("KMBH","科目编号");
            this.put("XHRQ","销户日期");
            this.put("YHDM","银行代码");
            this.put("YHMC","银行名称");
            this.put("YHZHHM","银行专户号码");
            this.put("YHZHMC","银行专户名称");
            this.put("ZHXZ","专户性质");
            this.put("cBankContract","签约银行");
            this.put("extension","银行专户信息扩展");
            // ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='银行专户信息表 表9.0.3';
        }};

}